### ISSUE TITLE
Get Meta Data

### ISSUE THREAD

**Issue by BassemN** [medariox/Scrapeer#4]
Hi,

Great library :+1: 
How can I get meta data like directory/torrent name ?

Thanks

**Comment by medariox** [comment]
Unfortunately, the [tracker scrape convention](https://wiki.theory.org/index.php/BitTorrentSpecification#Tracker_.27scrape.27_Convention) doesn't provide that kind of information. It has only information for completed, leechers, seeders and optionally the name of the torrent. Since the name is optional it is almost never included, at least for public trackers. Nonetheless, I will try to include it in the next major version.

To retrieve that kind of information you will need the torrent file and some library to BEncode the data. [torrent-bencode](https://github.com/bhutanio/torrent-bencode) can do that for example. Good luck!

**Comment by BassemN** [comment]
Thanks for getting back to me with your prompt reply.
